# Generated by Django 3.2.9 on 2022-11-17 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_auto_20221117_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worldcup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_game', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('game', models.IntegerField(default=0)),
                ('victory', models.IntegerField(default=0)),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
