# Generated by Django 3.2.9 on 2022-11-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor_count',
            old_name='count',
            new_name='cnt',
        ),
        migrations.RenameField(
            model_name='director_count',
            old_name='count',
            new_name='cnt',
        ),
        migrations.RenameField(
            model_name='genre_count',
            old_name='count',
            new_name='cnt',
        ),
        migrations.DeleteModel(
            name='Worldcup',
        ),
    ]
