# Generated by Django 3.2.9 on 2022-11-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendmovie',
            name='movie',
        ),
        migrations.AddField(
            model_name='recommendmovie',
            name='movie',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
        migrations.RemoveField(
            model_name='similarmovie',
            name='movie',
        ),
        migrations.AddField(
            model_name='similarmovie',
            name='movie',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
