# Generated by Django 3.2.9 on 2022-11-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('release_date', models.DateTimeField()),
                ('poster_path', models.CharField(max_length=200)),
                ('youtube_key', models.CharField(max_length=100)),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
