# Generated by Django 3.2.9 on 2022-11-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20221123_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='vote',
            field=models.FloatField(),
        ),
    ]
